name: Bandcamp Digest Generator

on:
  schedule:
    # Запускаем каждый четверг в 19:00 по Белграду (17:00 UTC)
    - cron: '0 17 * * 4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository  # Клонируем репозиторий
      uses: actions/checkout@v4

    - name: Set up Python         # Устанавливаем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies  # Устанавливаем зависимости (только requests и openai)
      run: pip install requests openai

    - name: Run Bandcamp digest generator  # Запускаем наш питоновский скрипт
      run: python bandcamp_digest.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Upload digest as artifact       # Сохраняем результат как артефакт GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: bandcamp-digest
        path: output/digest.md
        retention-days: 3
