name: Generate Bandcamp Digest

on:
  schedule:
    - cron: '0 17 * * 3'  # Каждую среду в 19:00 (GMT+2)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем зависимости
      - name: Install Python dependencies
        run: |
          pip install playwright openai
          playwright install chromium

      # Шаг 3: Запускаем скрипт генерации дайджеста
      - name: Run bandcamp_digest.py
        run: python bandcamp_digest.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # Шаг 4: Сохраняем markdown и JSON как артефакт
      - name: Upload generated digest
        uses: actions/upload-artifact@v4
        with:
          name: bandcamp-digest-${{ github.run_id }}
          path: |
            output/digest.md
            output/playwright_releases.json
          retention-days: 3
